[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:magicstar-platform]
directory=/app/magicstar-platform
command=python -m uvicorn app.main:app --host 0.0.0.0 --port 80
environment=SERVER_PORT="80"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dreamclip-service]
directory=/app/dreamclip-service
command=python -m uvicorn app.main:app --host 0.0.0.0 --port 8081
environment=SERVER_PORT="8081"
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
